export const LOAD_PLAYERS_SUCCESS = "LOAD_PLAYERS_SUCCESS";
export const LOAD_TOURNAMENTS_SUCCESS = "LOAD_TOURNAMENTS_SUCCESS";
export const LOAD_RACQUETS_SUCCESS = "LOAD_RACQUETS_SUCCESS";
export const CREATE_PLAYER_SUCCESS = "CREATE_PLAYER_SUCCESS";
export const UPDATE_PLAYER_SUCCESS = "UPDATE_PLAYER_SUCCESS";
export const DELETE_PLAYER_SUCCESS = "DELETE_PLAYER_SUCCESS";