/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        // Custom color palette
        tomato: {
          DEFAULT: "#f06543",
          50: "#fef6f4",
          100: "#fcebe7",
          200: "#f9ddd5",
          300: "#f4c2b6",
          400: "#ed9e8e",
          500: "#f06543",
          600: "#e04f31",
          700: "#bc3e26",
          800: "#9b3525",
          900: "#803125",
          950: "#451610",
        },
        "antiflash-white": {
          DEFAULT: "#e8e9eb",
          50: "#f8f8f9",
          100: "#f1f2f4",
          200: "#e8e9eb",
          300: "#d1d3d7",
          400: "#b4b7be",
          500: "#9ca1ab",
          600: "#878d99",
          700: "#777d87",
          800: "#646970",
          900: "#53575c",
          950: "#34373a",
        },
        alabaster: {
          DEFAULT: "#e0dfd5",
          50: "#f9f9f7",
          100: "#f3f2ed",
          200: "#e8e6db",
          300: "#e0dfd5",
          400: "#d0ccbb",
          500: "#c1bcaa",
          600: "#afa995",
          700: "#928c7a",
          800: "#787364",
          900: "#625e53",
          950: "#32302a",
        },
        onyx: {
          DEFAULT: "#313638",
          50: "#f6f6f7",
          100: "#ededef",
          200: "#d8d9dc",
          300: "#babcc2",
          400: "#969aa3",
          500: "#7a7f88",
          600: "#656971",
          700: "#53575c",
          800: "#474a4e",
          900: "#3e4144",
          950: "#313638",
        },
        "sandy-brown": {
          DEFAULT: "#f09d51",
          50: "#fef8f0",
          100: "#fdefdd",
          200: "#fbdcba",
          300: "#f7c28c",
          400: "#f2a05c",
          500: "#f09d51",
          600: "#e17829",
          700: "#bc601f",
          800: "#964d1e",
          900: "#7a411c",
          950: "#421f0b",
        },
        // shadcn/ui colors
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [],
};
