INSERT INTO customers (name, email, phone_number, address) VALUES ('Douglas Konopelski', 'Darron63@example.com', '(053) 412 42 36', '423 Kasey Green');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Roxanne Ankunding DDS', 'Fausto_Rosenbaum97@example.com', '(820) 475 08 77', '528 Jermey Cape');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Stewart Hamill', 'Sierra_Bradtke1@example.com', '(417) 114 48 76', '205 Pine Street');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Mandy Raynor', 'Robb7@example.com', '(375) 474 11 41', '335 Ortiz Passage');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Kerry Bechtelar', 'Verda.Bashirian98@example.com', '(448) 330 24 70', '99656 Felicia Glens');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Marian Parker', 'Terrell_Schimmel-Stracke14@example.com', '(758) 870 26 21', '928 Rosenbaum Fields');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Micheal Reilly', 'Dasia29@example.com', '(644) 039 83 19', '1396 Yost Forges');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Minnie Beier', 'Camden.Kunde47@example.com', '(666) 911 47 01', '4156 Candelario Islands');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Jana O''Kon', 'Emmanuel_Murray@example.com', '(500) 532 22 69', '424 Kovacek Hills');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Dr. Claude Mante', 'Hazel65@example.com', '(447) 496 90 52', '94888 Bailey Groves');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Rick Kozey', 'Helen_Trantow45@example.com', '(399) 935 78 99', '9708 Shields Hollow');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Pearl Schuppe', 'Ryder_Rempel17@example.com', '(913) 212 21 23', '73553 Mariane Ville');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Irving Treutel', 'Abelardo.Nolan9@example.com', '(999) 238 68 41', '8369 Raynor Groves');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Clay Glover', 'Wilber_Bogisich@example.com', '(427) 545 45 63', '308 E Elm Street');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Timothy Smitham IV', 'Kayli_Blick@example.com', '(962) 969 30 38', '50859 Elm Close');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Nichole Marks', 'Kieran.Corwin@example.com', '(055) 134 64 12', '7444 Broad Lane');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Mario Schmitt', 'Ethelyn_Herzog0@example.com', '(962) 758 87 41', '3854 Williamson Coves');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Fredrick Rogahn', 'George.Schmitt@example.com', '(794) 578 21 61', '2497 Schamberger Rapid');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Mr. Miguel Koch', 'Corine28@example.com', '(137) 749 63 57', '799 Smith Estate');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Pamela Lindgren III', 'Aditya79@example.com', '(784) 917 68 88', '47093 Bruen Dale');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Laverne Littel PhD', 'Vallie_Shanahan@example.com', '(002) 312 72 09', '63494 Jast Plaza');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Derek Dicki', 'Shanna_Roberts12@example.com', '(481) 024 11 81', '7558 Leffler Skyway');
INSERT INTO customers (name, email, phone_number, address) VALUES ('John Bogan II', 'Rylan35@example.com', '(647) 182 50 56', '8870 Park Avenue');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Gustavo Goodwin-Heller Sr.', 'Jackeline68@example.com', '(956) 559 66 23', '9128 Kutch Walks');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Evelyn Grady', 'Urban64@example.com', '(605) 264 42 40', '508 Karine Manor');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Florence Fadel', 'Andreanne_Waters55@example.com', '(970) 486 21 79', '476 W River Road');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Ida Hayes', 'Chaya.Schinner24@example.com', '(306) 569 29 86', '3383 Duane Well');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Cathy Roberts', 'Ashlynn.Mann94@example.com', '(110) 896 95 46', '6674 Mollie Knolls');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Dr. Rosie Gorczany Sr.', 'Noble_Glover@example.com', '(360) 115 81 23', '21297 Hane Islands');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Katherine Hills', 'Meredith_Franecki@example.com', '(076) 658 26 46', '272 Nash Brooks');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Carl Jones', 'Maximo.Zieme@example.com', '(705) 331 96 13', '9600 Avenue Road');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Brandy Bernhard', 'Nathanial.Cassin64@example.com', '(226) 083 11 70', '3137 Hane Run');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Clint Beatty', 'Dave_Wuckert69@example.com', '(481) 135 50 09', '1698 Dudley Row');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Ella Koch', 'Herminio_DuBuque@example.com', '(549) 763 28 88', '205 Station Road');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Raymond Brakus', 'Rosamond73@example.com', '(632) 614 71 96', '7261 Abernathy Gardens');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Genevieve Brekke', 'Enos.Jones@example.com', '(797) 118 22 58', '8151 N Center Street');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Leslie Shanahan', 'Aaliyah_Connelly23@example.com', '(998) 810 64 98', '500 Crown Street');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Lorene Franey', 'Reagan_Schroeder80@example.com', '(207) 571 36 39', '1663 Rectory Close');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Danielle Langosh MD', 'Jude9@example.com', '(308) 288 67 51', '774 Carlie Greens');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Andrea Spencer', 'Baron.Kreiger22@example.com', '(946) 414 42 69', '4844 Toy Shoal');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Billie Jakubowski', 'Parker_Bahringer@example.com', '(974) 986 24 93', '274 High Road');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Darnell Collier', 'Meta_Legros@example.com', '(389) 561 21 15', '2458 Swift Locks');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Shaun Medhurst', 'Terrence77@example.com', '(456) 810 47 45', '8223 Herminio Circle');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Ellen Becker', 'Adriel.Lynch95@example.com', '(487) 887 14 84', '21224 Jasen Way');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Nicole Koelpin', 'Rolando44@example.com', '(322) 658 58 24', '9305 Main Street N');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Frederick Gusikowski', 'Toby_Rogahn70@example.com', '(878) 464 40 07', '48823 Chester Road');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Kirk Konopelski', 'Angus89@example.com', '(131) 940 61 77', '63534 Schowalter Radial');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Melba Howe', 'Jaiden_Brakus45@example.com', '(589) 638 28 85', '88889 Silver Street');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Mr. Terence Sporer MD', 'Corine.Padberg58@example.com', '(278) 337 18 11', '394 Hills Plaza');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Sonya Moen', 'Nathen_Morissette@example.com', '(417) 894 77 44', '2714 Marianna Viaduct');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Mrs. Tami Gleichner', 'Cooper_Johnston87@example.com', '(464) 602 03 49', '35529 Darrick Court');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Agnes Predovic', 'Joy79@example.com', '(426) 797 27 17', '73729 Silas Point');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Beulah Zulauf', 'Reyes_Nienow@example.com', '(137) 346 63 12', '8227 Demario Villages');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Clara Prohaska MD', 'Myah_Rodriguez@example.com', '(727) 559 31 46', '9067 Grange Road');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Bobbie Ullrich DDS', 'Constance_Parker16@example.com', '(626) 967 23 71', '8770 George Street');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Melanie McDermott', 'Bessie.Daniel-Feil@example.com', '(208) 828 30 97', '3487 Kub Falls');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Grace Wolf', 'Gerard.Schroeder@example.com', '(371) 934 05 56', '8123 Alba Hill');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Bessie Schimmel-Satterfield', 'Louisa33@example.com', '(634) 979 57 67', '4942 Roma Stravenue');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Tomas Wisoky', 'Alta_Corwin@example.com', '(285) 478 75 97', '5177 Bay Street');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Martha McKenzie', 'Jayson_Bernhard@example.com', '(582) 957 29 55', '9866 Daniel Forge');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Kristi Padberg', 'Cortney48@example.com', '(729) 245 63 69', '9261 E 5th Street');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Nicholas Bosco', 'Evelyn_Koelpin@example.com', '(823) 867 15 63', '615 Stark Knoll');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Fannie Terry', 'Samara76@example.com', '(603) 009 22 34', '566 Shannon Garden');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Viola McKenzie', 'Anya_Murazik@example.com', '(651) 322 40 60', '57769 Duane Ways');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Mr. Barry Grimes', 'Alexanne78@example.com', '(298) 637 25 49', '578 Martin Luther King Boulevard');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Dallas Wunsch', 'Marianna83@example.com', '(618) 936 89 72', '18028 Jaleel Villages');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Clay Bruen Jr.', 'Taurean.Stiedemann91@example.com', '(586) 176 91 46', '85045 Arnaldo Meadows');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Amanda Fisher', 'Elvis15@example.com', '(581) 686 55 93', '8135 Market Square');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Mrs. Sandra Larkin', 'Thomas.Steuber12@example.com', '(882) 315 79 02', '2303 Sauer Walk');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Orlando Jones', 'Daniela99@example.com', '(051) 017 04 21', '33464 Gibson Place');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Terry Fay', 'Reanna_Hintz30@example.com', '(973) 305 18 48', '996 Broadway Avenue');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Erika Bode-Ledner', 'Paolo32@example.com', '(135) 798 21 23', '423 Ritchie Dale');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Corey Greenholt', 'Kaycee.Kautzer@example.com', '(239) 845 61 99', '9283 S Pine Street');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Alfred Green DDS', 'Mauricio_Toy94@example.com', '(208) 574 05 23', '20465 Lodge Lane');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Nora Franey MD', 'Ellie_Pfannerstill25@example.com', '(547) 214 10 05', '7979 Daniella Circle');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Dolores Satterfield', 'Lia82@example.com', '(694) 369 41 86', '78822 Camryn Falls');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Dwight McCullough', 'Wendy_Harvey@example.com', '(724) 024 23 05', '890 E Washington Street');
INSERT INTO customers (name, email, phone_number, address) VALUES ('James Rodriguez', 'Elza.Luettgen@example.com', '(381) 202 32 42', '46186 Schamberger Courts');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Luther Keeling', 'Carley78@example.com', '(730) 394 22 59', '4212 Rau Forge');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Owen King', 'Bailey.Waters@example.com', '(989) 157 49 60', '106 Ernser Curve');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Walter Harber', 'Mayra93@example.com', '(756) 352 42 67', '925 Ernesto Mews');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Clara Little', 'Amir_Gleichner@example.com', '(796) 534 32 45', '1141 Marks Run');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Terrell Von', 'Cullen.Kertzmann81@example.com', '(260) 910 02 62', '251 Murray Valley');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Woodrow Satterfield', 'Llewellyn.Stanton@example.com', '(501) 926 15 07', '435 Ted Island');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Lance Barton-Zemlak', 'Brycen.Daniel-Kihn12@example.com', '(613) 335 17 88', '388 Lemke Forest');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Peggy Gusikowski', 'Ellis_Tillman76@example.com', '(548) 928 31 14', '444 Greenwood Road');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Leslie Ledner', 'Kaylah.Runte39@example.com', '(966) 477 22 49', '753 Veum Key');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Heather Moore-Gusikowski', 'Vivianne_Olson@example.com', '(857) 425 98 78', '7534 Adams Street');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Donna Dach', 'Vince2@example.com', '(735) 168 72 80', '5197 Corine Prairie');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Erma Welch', 'Pierce66@example.com', '(560) 677 09 85', '82258 School Close');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Walter Rogahn', 'Shanon_Hoeger39@example.com', '(324) 480 47 91', '25521 Boundary Road');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Ervin Hermann', 'Clementine.Harber@example.com', '(885) 475 74 82', '147 Kayli Crest');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Rudolph Rutherford', 'Whitney37@example.com', '(893) 103 84 25', '9777 Shields Dale');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Guillermo O''Keefe-Boyle', 'Jack_Rosenbaum@example.com', '(820) 677 26 21', '6587 Rosina Stream');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Kristi Green', 'Peggie18@example.com', '(288) 268 03 57', '13015 Rosenbaum Mews');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Marcia Connelly', 'Jarrett.Heaney@example.com', '(033) 335 25 41', '52616 Jermain Square');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Janie Harber', 'Hector23@example.com', '(840) 125 92 08', '953 Schaden Stravenue');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Jerry Jenkins', 'Retta_Schuppe@example.com', '(745) 701 69 37', '188 Goyette Knoll');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Edwin Goyette', 'Terrell65@example.com', '(883) 118 30 07', '97500 Franklin Road');
INSERT INTO customers (name, email, phone_number, address) VALUES ('Courtney Rogahn-Bechtelar', 'Blair_Hagenes65@example.com', '(157) 887 02 25', '4128 Buckridge Lodge');

INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (1, 'Rolls Royce', '911', 2011, 'AUNGFDJE0MRE86189');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (2, 'Chevrolet', 'Expedition', 2000, '7T7B4139JND540491');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (3, 'Mini', 'LeBaron', 2000, '1US3BJHXC8ML46514');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (4, 'Rolls Royce', 'Silverado', 2000, '12E1VCHRXZZ339503');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (5, 'Mini', '911', 2000, '58133FRR86WM83880');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (6, 'Jeep', 'Cruze', 2000, 'VSX56LDX18NM11568');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (7, 'Cadillac', 'A4', 2000, '57UEME8047HT22901');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (8, 'Toyota', 'Camry', 2000, '9W0K9Y9JNVYD14965');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (9, 'Polestar', 'Fortwo', 2020, 'HLAE6H2P58DA20110');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (10, 'Nissan', 'Accord', 2000, 'E54AKANT0SA849456');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (11, 'Polestar', 'Fortwo', 2000, 'T0AM9X9G9APG80224');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (12, 'Dodge', 'Countach', 2022, 'RMRKH3U9TCE189780');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (13, 'Cadillac', 'Impala', 2000, 'ETYK0WPAKZZY17942');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (14, 'Porsche', 'Grand Cherokee', 2000, 'XM3CR5808TPR89450');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (15, 'Mercedes Benz', 'Alpine', 2000, 'RN4455RYUPJ110659');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (16, 'Land Rover', 'PT Cruiser', 2000, 'LADGZ5PV2MT118455');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (17, 'Ferrari', 'PT Cruiser', 2000, 'N8EYFZGDEJW633510');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (18, 'Rolls Royce', 'F-150', 1999, '761Z9ZVXMBDW15833');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (19, 'Dodge', 'Accord', 2000, 'B7FL0JP5L5T191379');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (20, 'Audi', 'Wrangler', 2000, '2Z44TTWJ2HVW89681');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (21, 'Ferrari', 'El Camino', 2000, 'RDPA5LV66CKX20159');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (22, 'Maserati', 'Silverado', 2000, 'WH03UZV0N2GG33869');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (23, 'Hyundai', 'Roadster', 2000, 'RSTBKHJ8G7JF47971');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (24, 'Jaguar', 'Grand Caravan', 2000, 'B7RZ8D7SUNP512229');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (25, 'BMW', '2', 2000, 'LT9EHWSGYBFH72827');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (26, 'Mazda', 'A8', 2000, 'ZM8FAE6A74R443136');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (27, 'Nissan', 'Camaro', 2000, 'GP9MAL1AUVC372584');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (28, 'Tesla', 'Accord', 2000, 'FWZCVBY2SNM920206');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (29, 'Polestar', 'Fiesta', 2000, '2KTYAW0FU3T217428');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (30, 'Polestar', 'Cruze', 2000, 'UPCAGUWDXJG643775');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (31, 'Jaguar', 'Escalade', 2000, 'LL8FNA975DAV52558');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (32, 'Volkswagen', 'ATS', 2000, 'U7HL6BSNV4BE27809');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (33, 'Rolls Royce', 'Roadster', 2000, 'UX969695MYRV17875');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (34, 'Polestar', 'Mustang', 2000, 'EWK1ULK6GZS455843');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (35, 'Jaguar', 'Countach', 2000, 'GH11H0ZBJ0DE84910');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (36, 'Volvo', 'Durango', 2000, 'ED9MCMEUJEFV19639');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (37, 'Mercedes Benz', 'Sentra', 2000, '1W0Y5EUJ2NV349460');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (38, 'Fiat', '1', 2000, 'SSG9UXD12NB633696');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (39, 'Jeep', 'Civic', 2000, 'L3MSP8Z0DSG992466');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (40, 'Cadillac', 'Sentra', 2000, 'CHSK7NBAW7Y349774');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (41, 'Ferrari', 'Civic', 2000, 'DL9CASRGUZPS92501');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (42, 'Chrysler', 'Roadster', 2000, 'SHNBHH7DZGF244161');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (43, 'Jeep', 'Roadster', 2000, 'A2NTYEF0TTSV92365');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (44, 'Kia', 'Colorado', 2000, '4HF01A0GC5J346855');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (45, 'Mini', 'XC90', 2000, 'DM48ZTPSXURF67630');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (46, 'Honda', '2', 2000, 'RZ3EW135BEA655135');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (47, 'Cadillac', 'A8', 2000, 'UWLKB8C9N9BF63459');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (48, 'Porsche', 'Camry', 2000, '2B1CRTS0KELT53620');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (49, 'Chevrolet', 'Charger', 2000, 'LW76HLJFNMUT64317');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (50, 'Aston Martin', 'Impala', 2000, '3A5XZ7JZRNHY35172');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (51, 'Kia', 'Roadster', 2030, 'NZBUF9CV65YR11514');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (52, 'Kia', 'Mercielago', 2000, 'VENDTY7CDNE557173');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (53, 'Rolls Royce', 'Corvette', 2000, 'L9N4X79UDKYN58433');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (54, 'Smart', 'Explorer', 2050, 'JE2JZ8GYL9TK75431');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (55, 'Lamborghini', 'Silverado', 2000, 'RAPYBRJYEYF831159');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (56, 'Rolls Royce', 'Ranchero', 2080, 'WSVMXANV4WDJ41902');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (57, 'Chevrolet', 'V90', 2000, 'ZDN3DHWAUGTC72699');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (58, 'Land Rover', 'PT Cruiser', 2090, 'J61R7RZ7C6ZY63136');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (59, 'Nissan', 'Model T', 2000, '6EY685EF1JJ689079');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (60, 'Tesla', 'XC90', 2000, '5YUB194DBXME23405');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (61, 'Ford', 'Mustang', 2000, 'ZGPVFS23PYMK37893');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (62, 'Polestar', 'Fiesta', 2000, 'CCNHT93BGTZZ18073');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (63, 'Fiat', 'Fiesta', 2000, 'U1J6CA87WMW296045');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (64, 'Cadillac', 'Corvette', 2000, 'DE0GKF8U8DHN94140');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (65, 'Chevrolet', 'Cruze', 2000, 'UUK46918J1UA84199');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (66, 'Porsche', 'Grand Caravan', 2000, 'CRHVGP0VJ1VA24358');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (67, 'Ford', 'Mercielago', 2000, '6GWHC5YDCMJJ99790');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (68, 'Hyundai', 'Taurus', 2000, 'PJ4YN6P5R1JP98444');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (69, 'Maserati', 'Model Y', 2000, 'H0S89WHMWJJT63622');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (70, 'Mercedes Benz', 'Camaro', 2000, 'HLXB7CBNRDXZ32034');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (71, 'Jaguar', 'Impala', 2000, 'BKGHZZGFZHZS76970');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (72, 'Mini', 'El Camino', 2000, '1R3CPV5X3ANW14393');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (73, 'Mazda', 'F-150', 2000, 'YBJPLZBB20ND43959');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (74, 'Honda', 'Prius', 2000, '84LH1BM7DRMH85813');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (75, 'Cadillac', 'Countach', 2000, 'RGN6BWR784HK64389');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (76, 'BMW', 'V90', 2000, 'S8JGG74ECPFV64049');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (77, 'Audi', 'Grand Caravan', 2000, '9MHZRT4LLNJZ83670');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (78, 'Jaguar', 'Camry', 2000, '4D927ABKNSAY29317');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (79, 'Maserati', 'Civic', 2000, 'XJX8N1ZRJNL436104');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (80, 'Volkswagen', 'LeBaron', 2000, '9SGAPK986WHX50046');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (81, 'Bentley', 'XC90', 2000, 'LPN82BW4B6CN57577');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (82, 'Toyota', 'Land Cruiser', 2000, '18N8CPXBTME365568');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (83, 'BMW', 'Sentra', 2000, 'GXPUJEZBD2MV47850');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (84, 'Volkswagen', 'Sentra', 2000, '61DULYJLEEJS95071');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (85, 'BMW', 'Countach', 2000, '1RJX8ZXLF2Z689459');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (86, 'Chrysler', '2', 2000, 'HD6XJ692BNC147335');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (87, 'BMW', 'Altima', 2000, 'ZPDCLGNL7BJ439081');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (88, 'Hyundai', 'F-150', 2000, 'M4C6U9CAX9WU67023');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (89, 'Land Rover', 'A8', 2000, '6ZEA69448XYK52206');
INSERT INTO vehicles (customer_id, make, model, "year", license_plate) VALUES (90, 'Jeep', 'XTS', 2000, 'MPPA0D5XM9DU63939');

INSERT INTO repair_orders (vehicle_id, description, status) VALUES (1, 'Utrimque confido approbo curto curia.', 0);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (2, 'Credo alter casus possimus. Patior utroque accusamus cicuta cur caveo adulescens canto. Tamen uter cito taceo statua delego adamo tardus deporto ars.\nCiminatio tenax concido conatus deduco sto quod volutabrum depereo succedo. Suasoria decimus deputo considero tui claro comedo coaegresco curatio abeo. Spes omnis victus decimus demulceo.\nBonus nihil creator amitto deficio tabula. Decor viscus ascit textus curto victoria comis ducimus. Umerus summa tempore aliquid adfectus molestiae soluta aestus color.', 2);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (3, 'Caelum modi in inventore thymbra aegrotatio.\nAlii veritas corrumpo amaritudo apparatus arceo.\nConor vestigium catena ater amitto abeo molestias coerceo campana corrumpo.\nConforto ratione acquiro verbum harum sublime adamo subnecto coniuratio.', 3);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (4, 'Ventus vae pax tamisium atavus valens vinco confero catena. Maiores subseco asperiores arma currus vinum combibo spectaculum. Ratione comburo amor eveniet consectetur absens synagoga patruus capitulus.', 4);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (5, 'Conspergo dens deripio vicinus temporibus facere victus aetas decipio pecco.\nAdimpleo celer consequatur spero tunc aestas.\nAsperiores accendo curvo admiratio adipiscor vorago nemo curatio.\nUmerus vigilo eum.\nDelectus terra celo tredecim dolore abutor.', 5);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (6, 'Adimpleo tempus coaegresco libero tenus voluntarius desolo. Curtus subito summa ager balbus appositus iure. Derideo suadeo sum ratione.\nAdversus concido dolor tam arx alveus. Tactus nulla pariatur amaritudo vereor crustulum cras deporto corpus. Dolore denego theologus consuasor adsuesco.\nCena annus et cado. Nobis adficio neque ulciscor suppellex ea talus tamisium celebrer suffoco. Suspendo congregatio architecto vesper.', 5);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (7, 'Decumbo consuasor minus tricesimus quos.\nTheologus temperantia deludo tumultus advenio degusto error.\nAcsi ad sit cuppedia charisma abscido sui uxor.\nRepudiandae tyrannus illo depromo quos tergeo atrox utpote.\nQuo possimus balbus.', 2);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (8, 'Molestias undique usus amplitudo.', 2);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (9, 'Vox clementia astrum coniecto viriliter torqueo conculco corrigo laudantium verumtamen. Degenero virgo deorsum eius animi pauci. Verus debeo aegre quae.', 2);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (10, 'Vobis careo paens. Texo audentia aufero cimentarius turpis patrocinor certus. Cresco comminor cauda civis cilicium pauper aeger adipisci delinquo claro.', 2);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (11, 'Sub claustrum cras tremo. Tenuis subvenio vapulus aeger. Demoror torqueo adipisci sufficio.', 2);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (12, 'Auxilium ocer sodalitas cornu. Non amoveo colligo. Valetudo xiphias canonicus ante subiungo. Compono esse theca cotidie debilito vinculum volaticus cavus.', 2);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (13, 'Adopto capitulus corpus damno. Cohibeo tabgo solitudo copia timor artificiose. Tantillus contigo aduro curiositas demonstro sapiente aliquam pecco.', 2);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (14, 'Summa nam catena timor sint agnosco timidus. Quibusdam pecus cupiditas campana. Sponte advoco arbustum necessitatibus.\nQuas somnus taedium. Adiuvo termes cinis acerbitas talus certus aqua adnuo sunt pecco. Canonicus utique tempus vestigium crudelis.\nConsuasor curo cetera derelinquo tumultus ars contego solvo collum earum. Conicio voveo voro enim calculus alo. Summa usitas vetus stella turbo absconditus et paens.', 2);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (15, 'Solium vulgo comis verbera valetudo ater vero aegrotatio virgo credo.', 2);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (16, 'Accendo fuga quis molestiae thermae baiulus sunt. Conservo curriculum clibanus ubi corona asperiores vero adaugeo cunctatio degenero. Vinum conturbo solvo virga creber adipiscor denuncio ab.\nUtroque temeritas antepono umerus tenuis solum. Vinco coniuratio demens quis nobis. Carcer paens abscido defluo.\nVilis statim cursus tres totidem. Vociferor cubo attollo credo despecto. Ager adsuesco peccatus celebrer utroque curto peior vorago arcus.', 2);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (17, 'Damnatio adstringo deficio verecundia anser soleo ad aedificium. Sortitus claustrum tertius asporto quam aequus conduco. Supplanto annus surgo quas absconditus tubineus delibero collum.', 2);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (18, 'Subseco sum beneficium adicio agnitio fuga.', 2);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (19, 'Temptatio absens cattus temeritas tibi vito vobis.', 2);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (20, 'Accusamus adhaero caterva claustrum.\nTemperantia sui suspendo cena ut.', 2);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (1, 'Utrimque confido approbo curto curia.', 2);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (2, 'Credo alter casus possimus. Patior utroque accusamus cicuta cur caveo adulescens canto. Tamen uter cito taceo statua delego adamo tardus deporto ars.\nCiminatio tenax concido conatus deduco sto quod volutabrum depereo succedo. Suasoria decimus deputo considero tui claro comedo coaegresco curatio abeo. Spes omnis victus decimus demulceo.\nBonus nihil creator amitto deficio tabula. Decor viscus ascit textus curto victoria comis ducimus. Umerus summa tempore aliquid adfectus molestiae soluta aestus color.', 1);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (3, 'Caelum modi in inventore thymbra aegrotatio.\nAlii veritas corrumpo amaritudo apparatus arceo.\nConor vestigium catena ater amitto abeo molestias coerceo campana corrumpo.\nConforto ratione acquiro verbum harum sublime adamo subnecto coniuratio.', 4);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (4, 'Ventus vae pax tamisium atavus valens vinco confero catena. Maiores subseco asperiores arma currus vinum combibo spectaculum. Ratione comburo amor eveniet consectetur absens synagoga patruus capitulus.', 1);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (5, 'Conspergo dens deripio vicinus temporibus facere victus aetas decipio pecco.\nAdimpleo celer consequatur spero tunc aestas.\nAsperiores accendo curvo admiratio adipiscor vorago nemo curatio.\nUmerus vigilo eum.\nDelectus terra celo tredecim dolore abutor.', 5);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (6, 'Adimpleo tempus coaegresco libero tenus voluntarius desolo. Curtus subito summa ager balbus appositus iure. Derideo suadeo sum ratione.\nAdversus concido dolor tam arx alveus. Tactus nulla pariatur amaritudo vereor crustulum cras deporto corpus. Dolore denego theologus consuasor adsuesco.\nCena annus et cado. Nobis adficio neque ulciscor suppellex ea talus tamisium celebrer suffoco. Suspendo congregatio architecto vesper.', 1);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (7, 'Decumbo consuasor minus tricesimus quos.\nTheologus temperantia deludo tumultus advenio degusto error.\nAcsi ad sit cuppedia charisma abscido sui uxor.\nRepudiandae tyrannus illo depromo quos tergeo atrox utpote.\nQuo possimus balbus.', 5);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (8, 'Molestias undique usus amplitudo.', 4);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (9, 'Vox clementia astrum coniecto viriliter torqueo conculco corrigo laudantium verumtamen. Degenero virgo deorsum eius animi pauci. Verus debeo aegre quae.', 5);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (10, 'Vobis careo paens. Texo audentia aufero cimentarius turpis patrocinor certus. Cresco comminor cauda civis cilicium pauper aeger adipisci delinquo claro.', 4);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (11, 'Sub claustrum cras tremo. Tenuis subvenio vapulus aeger. Demoror torqueo adipisci sufficio.', 4);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (12, 'Auxilium ocer sodalitas cornu. Non amoveo colligo. Valetudo xiphias canonicus ante subiungo. Compono esse theca cotidie debilito vinculum volaticus cavus.', 0);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (13, 'Adopto capitulus corpus damno. Cohibeo tabgo solitudo copia timor artificiose. Tantillus contigo aduro curiositas demonstro sapiente aliquam pecco.', 2);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (14, 'Summa nam catena timor sint agnosco timidus. Quibusdam pecus cupiditas campana. Sponte advoco arbustum necessitatibus.\nQuas somnus taedium. Adiuvo termes cinis acerbitas talus certus aqua adnuo sunt pecco. Canonicus utique tempus vestigium crudelis.\nConsuasor curo cetera derelinquo tumultus ars contego solvo collum earum. Conicio voveo voro enim calculus alo. Summa usitas vetus stella turbo absconditus et paens.', 1);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (15, 'Solium vulgo comis verbera valetudo ater vero aegrotatio virgo credo.', 2);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (16, 'Accendo fuga quis molestiae thermae baiulus sunt. Conservo curriculum clibanus ubi corona asperiores vero adaugeo cunctatio degenero. Vinum conturbo solvo virga creber adipiscor denuncio ab.\nUtroque temeritas antepono umerus tenuis solum. Vinco coniuratio demens quis nobis. Carcer paens abscido defluo.\nVilis statim cursus tres totidem. Vociferor cubo attollo credo despecto. Ager adsuesco peccatus celebrer utroque curto peior vorago arcus.', 1);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (17, 'Damnatio adstringo deficio verecundia anser soleo ad aedificium. Sortitus claustrum tertius asporto quam aequus conduco. Supplanto annus surgo quas absconditus tubineus delibero collum.', 4);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (18, 'Subseco sum beneficium adicio agnitio fuga.', 0);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (19, 'Temptatio absens cattus temeritas tibi vito vobis.', 4);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (20, 'Accusamus adhaero caterva claustrum.\nTemperantia sui suspendo cena ut.', 1);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (21, 'Vox advenio comitatus tubineus adimpleo cito voco. Comitatus tabesco clementia. Tamisium verus amaritudo.\nConduco ambitus desidero adstringo bardus cado aetas. Adulatio contabesco color quidem soleo. Sonitus cunae modi demonstro curto.\nAggredior amissio stultus undique blanditiis. Argumentum absorbeo facilis officia timidus clibanus. Timidus thymum tergo aqua eligendi peccatus quos.', 3);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (22, 'Texo avaritia comptus. Territo tabella crepusculum alioqui trucido. Strenuus carpo alioqui trans uberrime.\nSuccedo voluntarius video tui artificiose qui nulla confugo quod. Victus agnosco magnam aspicio spectaculum demergo comburo. Eaque surculus balbus eligendi bonus ultio creptio denego demergo.\nDefluo succurro vaco utroque sollers aequus. Amitto comprehendo termes minima attonbitus villa illum tenuis super corpus. Admoneo adaugeo tepesco ascisco ventosus optio dedico terreo.', 0);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (23, 'Illo avarus corroboro voluptas nulla adsidue.\nPauci calcar compono temeritas maxime decipio ventus.\nTerga sponte calamitas crapula ulciscor tam umbra apostolus.', 4);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (24, 'Acervus amplitudo depulso peior adstringo tutis candidus tabernus. Crudelis umquam supra theatrum vinco creta benevolentia articulus. Vae praesentium doloremque cupio volup deficio benigne vicinus adficio.\nEa cogo careo comminor. Vinitor creber cauda patruus deorsum truculenter ambitus fugit. Pectus vester terga molestias tripudio torrens vorago sophismata triduana.\nCorrigo tripudio contego comptus aedificium surgo demum thesaurus decumbo talis. Carbo vomica quos aptus argumentum. Spectaculum ustulo ventus uberrime victus.', 5);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (25, 'Speculum tantillus arbor pax sed quidem adaugeo patruus occaecati.\nConforto calco apud voluptas templum audacia aqua.\nCreator sophismata tergum.\nAntea quibusdam ab acies apto vetus officia acies terror.', 4);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (26, 'Soluta taedium quae adfectus tubineus creta sufficio vulariter cupressus ab.\nCumque delectus conspergo libero caelestis turbo.\nTexo suggero tenetur corrigo una calculus nesciunt anser.\nDedico vulnero sulum.', 0);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (27, 'Nobis porro ulterius sopor adflicto tredecim sequi atrocitas canonicus. Uxor calco expedita fuga vado coadunatio collum. Condico utrimque cruciamentum amplus viridis solus. Uter thymum infit. Sono pecus subnecto natus demum mollitia utrum cometes comedo.', 4);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (28, 'Facere claudeo vix animadverto thesis explicabo titulus perferendis tabula cornu. Territo textus thesaurus suus avaritia vomito sollers aureus adicio averto. Subvenio usque cribro cicuta defaeco tum nam claro.\nAmissio degusto benigne. Temperantia conicio tolero deduco auxilium at cena stella vehemens. Deleniti minus abutor conicio tamisium caecus adfero.\nAd tonsor cubicularis defero optio vaco suus ipsa. Antea amita vado pecco terga. Canis defetiscor aetas a dolor.', 1);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (29, 'Bardus sonitus traho utrum accusamus abeo ulterius commodi quas. Terror trucido accommodo. Apud colligo vociferor aeternus cohaero.\nTemptatio summisse officia ulterius aequus copiose vel. Talus adicio capillus annus natus cur in peior. Ventito casso utrimque tamen congregatio supellex ciminatio facilis strenuus.\nVerto virtus ocer vilis cultellus minus deduco cupio. Valens bis non atqui tristis depromo supra suspendo aurum adfero. Abstergo deserunt vae contego nisi sol.', 5);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (30, 'Carmen abstergo amita coepi vindico cavus. Solutio vesco cubicularis id correptius. Deduco averto triduana arcesso curso addo conatus absorbeo verus. Conicio uberrime nihil vobis crastinus animus termes.', 5);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (31, 'Amicitia appello alius.', 3);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (32, 'Spes temeritas turbo. Volva decumbo est curto terra amaritudo cunabula desparatus supra civis. Deludo amo tempus texo.', 5);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (33, 'Pauci ars corporis aeternus corona careo.', 1);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (34, 'Thema minima suggero arma sollicito solio torrens. Decumbo ambulo dedico ullus vobis tenuis cupio debeo atrox caelestis. Comes tum rem creo tabula doloremque nam ciminatio summa dedico.\nNulla minima umquam. Tam clibanus adinventitias acies auditor vespillo comminor suggero correptius derelinquo. Attollo cito non tabesco iure.\nPorro adulatio caute tametsi pectus trans adipisci. Appositus summopere villa debilito. Aequus eum terminatio turba.', 4);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (35, 'Vigilo pectus carpo in bellicus tamisium urbs.', 4);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (36, 'Somniculosus condico culpo celer delicate undique. Calcar contego tollo. Sui dolore baiulus congregatio pariatur.', 5);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (37, 'Autem aggredior unus maiores cubitum corrumpo accendo totam. Caries deprecator carpo deprimo odit cibus xiphias. Thermae volva celebrer demoror advenio clementia aperte adduco vivo. Cavus circumvenio spoliatio. Bestia super appono thema molestias attonbitus. Tum adulescens spoliatio volo laborum velut.', 5);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (38, 'Balbus aeternus cultellus casus clarus talus administratio cornu ambulo. Catena tersus tego accedo aqua adeo surgo timidus synagoga. Vitae censura sperno.', 0);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (39, 'Inflammatio aegrotatio calcar thema mollitia vester vero tracto. Color attollo denuo tres arbor. Animi ait vinculum.', 0);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (40, 'Quisquam vitiosus peccatus aurum undique uredo tamen conculco ab. Caute nulla vos torqueo caelestis summopere conservo. Cogito cupiditas curtus bene ambitus spiculum tracto congregatio.\nBardus averto cenaculum cursim. Canis eveniet bis torrens fugiat condico cetera advenio atrocitas aureus. Suscipit sponte comitatus.\nArca vomito nobis creta textus. Adopto vulariter in atrox aurum cinis sordeo. Thema atavus testimonium clarus calcar quam.', 0);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (41, 'Celo asperiores aestus tergo creta atque neque cras. Tergo aeger sordeo patior aiunt viduo decet. Desipio cupiditate apud fugiat amita.', 0);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (42, 'Condico abundans aiunt. Conculco confugo delicate voco veniam sophismata nemo adduco. At velociter auctus admitto cognomen paens vae complectus coma.', 3);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (43, 'Taceo cunctatio ocer trucido umbra bellum comminor. Amplitudo cursus versus victus deputo voluptas bardus.', 1);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (44, 'Decerno viriliter arbor vergo cuppedia speculum avaritia surculus aro benevolentia.\nRepudiandae utilis non auctus cupiditate damno substantia ex clarus depopulo.\nColligo canto catena antepono vallum magnam amitto in.\nQuod stipes termes deporto curtus commodi thalassinus.\nAncilla tabula adicio calco dolorum facere clibanus cunae alias valde.', 1);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (45, 'Dolor agnitio demulceo saepe. Adulescens utor veniam. Libero degenero vilis auditor vos cervus video.', 2);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (46, 'Denique synagoga vinco cimentarius defluo vulgivagus suppellex voluptas ceno. Incidunt virga comparo tyrannus. Canto adipiscor dapifer.\nVoro alter decens viriliter validus alveus temperantia modi temptatio. Sol votum conculco desolo vinculum tantillus deserunt charisma. Excepturi vinum cupiditas sono nulla undique vae.\nEos sordeo creber at libero odio. Corrupti dedico atrocitas distinctio. Creta coniecto usque vinitor tepesco damnatio barba occaecati amplitudo.', 4);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (47, 'Soleo amitto tergo centum socius corona cum. Venustas aegrotatio consuasor caelestis. Ipsum adsum asper tabgo.', 4);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (48, 'Urbs spes thymbra cilicium cavus audio. Carmen deporto bibo cohaero agnosco arma officiis. Quisquam substantia defungo creptio.\nAsporto claudeo arx adduco complectus argumentum inventore. Iusto tempus vivo conor confugo deputo acervus. Baiulus angulus suscipit agnosco administratio sono.\nMolestias triduana ascisco cinis quidem corporis laboriosam. Subiungo aggero cohaero. Tamisium sulum curto.', 3);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (49, 'Verto tamquam vorago accendo soleo demulceo. Cauda sortitus coerceo aufero. Eveniet aestas doloremque capio absorbeo vorax sint color volutabrum.\nVicissitudo aperiam at umerus angustus amo sordeo derideo. Decens cruciamentum auditor trucido aegrus. Id vehemens defleo.\nAduro cui nemo calculus. Volva ceno tardus antepono. Curso commemoro uterque adamo deripio.', 4);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (50, 'Autus creber depopulo nesciunt cursim qui adsuesco possimus vinitor. Dolorem accommodo casus auctus comedo carpo cohaero alii usus. Tremo urbanus tendo caste repellendus. Utrum omnis at. Adimpleo suggero atque terreo.', 0);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (51, 'Eveniet alo suasoria cenaculum bos.', 3);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (52, 'Carpo perspiciatis harum cinis facere vilitas dolor. Sopor adversus supellex. Umerus rerum vulnero tamdiu damnatio adflicto thymum torrens.', 0);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (53, 'Cimentarius titulus illo defendo sopor suscipit. Vindico tener conventus aequitas decretum comburo. Conturbo solutio suspendo soluta cedo.', 4);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (54, 'Aspernatur admoneo damnatio testimonium absorbeo damno abutor baiulus suggero alienus.', 1);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (55, 'Conservo armarium debilito bellicus cultellus abscido adaugeo. Concedo coadunatio celo deficio tristis. Cursus ullus molestiae quasi accusator. Demitto culpa clementia.', 5);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (56, 'Vulpes defetiscor armarium.', 5);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (57, 'Celebrer asperiores abstergo crinis suscipit crinis crur turbo verumtamen tui. Custodia corpus vix apud comedo calculus. Conforto vitium possimus curvo tracto sumptus.', 2);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (58, 'Socius admiratio supplanto altus.', 0);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (59, 'Dolore vere certe atavus.\nVereor corrigo admoveo crastinus creptio villa subvenio deporto.\nCaries adsum vado crustulum sodalitas.', 0);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (60, 'Vero adsum iure sortitus cilicium corrupti contra. Anser adflicto curvo asperiores tempus tero beatus absconditus attollo. Socius cunae curtus velociter exercitationem depulso. Territo argentum comprehendo turpis vilis degenero aggero thorax charisma quo. Harum cupiditate peccatus cura spiculum templum audacia ducimus demergo terreo.', 5);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (61, 'Abscido usus cariosus aestus sol sumptus velut tum.\nPaens sopor perspiciatis antea caput urbanus curiositas.\nTrans voluntarius vacuus theologus bene cognatus undique atavus ipsum.\nCentum somniculosus ullam debilito desidero vestrum debitis.\nConvoco cometes vis tumultus sonitus abeo tendo tempus.', 4);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (62, 'Tot patrocinor distinctio apud tactus ultra deorsum.', 4);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (63, 'Versus aliquid cras contra incidunt delectus ultra.', 1);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (64, 'Conatus considero conforto contabesco inventore cupio umbra tendo thema apostolus. Virga statim summisse asporto aranea conicio amoveo ater arto. Celer admoveo defessus abscido sto curso.', 1);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (65, 'Cohors bibo soluta tersus sint eveniet.', 5);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (66, 'Voluptas verecundia texo cursim. Argentum libero ipsa unde accusamus totidem. Triumphus blandior utrum distinctio tum atavus.', 1);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (67, 'Caput templum culpo. Facilis harum apud clarus somniculosus aggero. Copiose sustineo angelus curiositas caveo aeneus calcar cauda.', 4);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (68, 'Civis quibusdam comedo absconditus peior laudantium aggero odio bene. Magni adversus universe laborum aetas carpo cruentus tutis facere artificiose. Creator quidem cedo arto vomer demonstro cur.', 3);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (69, 'Viscus vicissitudo at viduo tondeo tener.', 3);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (70, 'Bos demulceo trans cernuus.', 2);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (71, 'Recusandae confugo cogito sunt adstringo.', 0);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (72, 'Utrum deputo ceno. Desipio quisquam arbor.', 2);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (73, 'Tabula aduro crux deludo volubilis. Sulum nesciunt suus terminatio corona bibo peccatus circumvenio. Vergo vox arto depono amissio summa acervus avarus.\nAdipisci tabella doloribus incidunt tepidus sumptus timor statim sumo vulticulus. Enim urbs tam tibi aegre. Traho corona vorago terminatio aegrus patrocinor tabernus abbas viriliter credo.\nBenigne iure accusantium conspergo supellex statua tantillus. Tendo ex allatus cura vel cresco tot deprimo. Itaque absque creptio voro comparo bos.', 0);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (74, 'Comitatus tendo magnam alias ter acquiro demergo super thalassinus allatus. Audentia sol corrigo tum usque.', 0);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (75, 'Auxilium adfero cauda amicitia defungo quia alienus aiunt suffragium.\nDucimus deprecator sortitus amet cohibeo tenuis tantillus adamo suggero.\nDeserunt candidus repellendus.\nVia argentum capio stipes nesciunt.', 5);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (76, 'Reprehenderit valde defaeco. Acer facere viscus deleniti doloremque crepusculum eveniet alveus commemoro damnatio. Sum demens maiores demo subiungo aqua urbanus thalassinus conqueror.', 2);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (77, 'Sordeo spoliatio animi spero solio conspergo tametsi. Calcar conturbo averto vero. Allatus undique voluptate crebro volo addo xiphias.\nAltus accusator arcus concedo alias absum ascit excepturi. Terreo surculus animus turpis colo corpus viriliter. Adfectus summa magnam surculus tenus.\nTremo villa alii arcus. Degero est sophismata vulgus patrocinor delectus commodi odit. Suffoco color vulgaris.', 3);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (78, 'Subito audentia deserunt.\nAntiquus tergum cubicularis caelestis suggero thymum.\nPectus natus aestivus altus suscipit tepesco rerum.\nBaiulus curso animadverto cohibeo.\nCicuta desidero vespillo volo bonus decerno spiritus.', 1);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (79, 'Appositus doloribus dolorem. Adeo validus vinitor infit. Virga sperno soluta accommodo.', 5);
INSERT INTO repair_orders (vehicle_id, description, status) VALUES (80, 'Thesis virga suscipit vado bos stella adeptio.\nStatim talio arto aranea dedecor.', 1);
