version: "3"
services:
  app:
    image: vinyl-app:latest
    container_name: 'vinyl-app'
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
  prometheus:
    image: prom/prometheus:latest
    container_name: 'prometheus'
    volumes:
      - ./devops/monitoring/prometheus/:/etc/prometheus/
    ports:
      - '9090:9090'
  grafana:
    image: grafana/grafana:latest
    container_name: 'grafana'
    ports:
      - '3000:3000'
    volumes:
      - ./devops/monitoring/grafana/provisioning/:/etc/grafana/provisioning/
      - ./devops/monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    env_file:
      - ./devops/monitoring/grafana/config.monitoring
    depends_on:
      - prometheus