start-dev:
	mvn clean package;
	java -jar target/interview-1.0-SNAPSHOT.jar --spring.profiles.active=dev;

start-prod:
	mvn clean package;
	java -jar target/interview-1.0-SNAPSHOT.jar;

sync-deps:
	mvn clean install;
