export const moviesMock = [
  {
    adult: false,
    backdrop_path: "/88DDOXggxZLxobBolSRRLkaS8h7.jpg",
    id: 1263256,
    title: "Happy Gilmore 2",
    original_title: "Happy Gilmore 2",
    overview:
      "Happy Gilmore isn't done with golf — not by a long shot. Since his retirement after his first Tour Championship win, Gilmore returns to finance his daughter's ballet classes.",
    poster_path: "/ynT06XivgBDkg7AtbDbX1dJeBGY.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [35],
    popularity: 372.098,
    release_date: "2025-07-25",
    video: false,
    vote_average: 6.821,
    vote_count: 209,
  },
  {
    adult: false,
    backdrop_path: "/7Zx3wDG5bBtcfk8lcnCWDOLM4Y4.jpg",
    id: 552524,
    title: "Lilo & Stitch",
    original_title: "Lilo & Stitch",
    overview:
      "The wildly funny and touching story of a lonely Hawaiian girl and the fugitive alien who helps to mend her broken family.",
    poster_path: "/c32TsWLES7kL1uy6fF03V67AIYX.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [10751, 878, 35, 12],
    popularity: 607.9262,
    release_date: "2025-05-17",
    video: false,
    vote_average: 7.337,
    vote_count: 1118,
  },
  {
    adult: false,
    backdrop_path: "/s94NjfKkcSczZ1FembwmQZwsuwY.jpg",
    id: 617126,
    title: "The Fantastic 4: First Steps",
    original_title: "The Fantastic 4: First Steps",
    overview:
      "Against the vibrant backdrop of a 1960s-inspired, retro-futuristic world, Marvel's First Family is forced to balance their roles as heroes with the strength of their family bond, while defending Earth from a ravenous space god called Galactus and his enigmatic Herald, Silver Surfer.",
    poster_path: "/x26MtUlwtWD26d0G0FXcppxCJio.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [878, 12],
    popularity: 369.8492,
    release_date: "2025-07-23",
    video: false,
    vote_average: 7.337,
    vote_count: 454,
  },
  {
    adult: false,
    backdrop_path: "/ApRxyHFuvv5yghedxXPJSm9FEDe.jpg",
    id: 1061474,
    title: "Superman",
    original_title: "Superman",
    overview:
      "Superman, a journalist in Metropolis, embarks on a journey to reconcile his Kryptonian heritage with his human upbringing as Clark Kent.",
    poster_path: "/ombsmhYUqR4qqOLOxAyr5V8hbyv.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [878, 12, 28],
    popularity: 320.7292,
    release_date: "2025-07-09",
    video: false,
    vote_average: 7.4,
    vote_count: 1226,
  },
  {
    adult: false,
    backdrop_path: "/As7NuiDRM4EO7LlJn2u8JWWsABp.jpg",
    id: 9614,
    title: "Happy Gilmore",
    original_title: "Happy Gilmore",
    overview:
      "Failed hockey player-turned-golf whiz Happy Gilmore — whose unconventional approach and antics on the green courts the ire of rival Shooter McGavin — is determined to win a PGA tournament so he can save his granny's house with the prize money. Meanwhile, an attractive tour publicist tries to soften Happy's image.",
    poster_path: "/epFP29rGrLPseuKxpz3mGKr23Do.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [35],
    popularity: 85.6721,
    release_date: "1996-02-16",
    video: false,
    vote_average: 6.654,
    vote_count: 2891,
  },
  {
    adult: false,
    backdrop_path: "/qwK9soQmmJ7kRdjLZVXblw3g7AQ.jpg",
    id: 7451,
    title: "xXx",
    original_title: "xXx",
    overview:
      'Xander Cage is your standard adrenaline junkie with no fear and a lousy attitude. When the US Government "recruits" him to go on a mission, he\'s not exactly thrilled. His mission: to gather information on an organization that may just be planning the destruction of the world, led by the nihilistic Yorgi.',
    poster_path: "/xeEw3eLeSFmJgXZzmF2Efww0q3s.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [28, 12, 53, 80],
    popularity: 142.5236,
    release_date: "2002-08-09",
    video: false,
    vote_average: 5.955,
    vote_count: 4487,
  },
  {
    adult: false,
    backdrop_path: "/ySHUoK4utUOiSfCinw81H1TsV0E.jpg",
    id: 1241470,
    title: "Osiris",
    original_title: "Osiris",
    overview:
      "Special Forces commandos on a mission are abducted mid-operation by a mysterious spacecraft. Upon waking aboard, they find themselves prey to a relentless alien race in a fight for survival.",
    poster_path: "/3YtZHtXPNG5AleisgEatEfZOT2w.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [878, 28, 27],
    popularity: 29.3781,
    release_date: "2025-07-25",
    video: false,
    vote_average: 6.056,
    vote_count: 18,
  },
  {
    adult: false,
    backdrop_path: "/8J6UlIFcU7eZfq9iCLbgc8Auklg.jpg",
    id: 1087192,
    title: "How to Train Your Dragon",
    original_title: "How to Train Your Dragon",
    overview:
      "On the rugged isle of Berk, where Vikings and dragons have been bitter enemies for generations, Hiccup stands apart, defying centuries of tradition when he befriends Toothless, a feared Night Fury dragon. Their unlikely bond reveals the true nature of dragons, challenging the very foundations of Viking society.",
    poster_path: "/41dfWUWtg1kUZcJYe6Zk6ewxzMu.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [14, 10751, 28],
    popularity: 793.171,
    release_date: "2025-06-06",
    video: false,
    vote_average: 8.08,
    vote_count: 1276,
  },
  {
    adult: false,
    backdrop_path: "/rthMuZfFv4fqEU4JVbgSW9wQ8rs.jpg",
    id: 986056,
    title: "Thunderbolts*",
    original_title: "Thunderbolts*",
    overview:
      "After finding themselves ensnared in a death trap, seven disillusioned castoffs must embark on a dangerous mission that will force them to confront the darkest corners of their pasts.",
    poster_path: "/hqcexYHbiTBfDIdDWxrxPtVndBX.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [28, 878, 12],
    popularity: 216.9315,
    release_date: "2025-04-30",
    video: false,
    vote_average: 7.402,
    vote_count: 2025,
  },
  {
    adult: false,
    backdrop_path: "/jvpkBenB6hv19WWYVlaiow8zklq.jpg",
    id: 1175942,
    title: "The Bad Guys 2",
    original_title: "The Bad Guys 2",
    overview:
      "The now-reformed Bad Guys are trying (very, very hard) to be good, but instead find themselves hijacked into a high-stakes, globe-trotting heist, masterminded by a new team of criminals they never saw coming: The Bad Girls.",
    poster_path: "/iPYgLLhQ69vIvgDtGFtAln4TYtM.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [10751, 35, 80, 12, 16],
    popularity: 51.8405,
    release_date: "2025-07-24",
    video: false,
    vote_average: 8.429,
    vote_count: 7,
  },
  {
    adult: false,
    backdrop_path: "/lqwwGkwJHtz9QgKtz4zeY19YgDg.jpg",
    id: 1136867,
    title: "Materialists",
    original_title: "Materialists",
    overview:
      "A young, ambitious New York City matchmaker finds herself torn between the perfect match and her imperfect ex.",
    poster_path: "/eDo0pNruy0Qgj6BdTyHIR4cxHY8.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [10749, 18],
    popularity: 133.7825,
    release_date: "2025-06-12",
    video: false,
    vote_average: 6.704,
    vote_count: 195,
  },
  {
    adult: false,
    backdrop_path: "/lSbblLngbeZIn6G4WXDcyQ6SLhw.jpg",
    id: 911430,
    title: "F1",
    original_title: "F1",
    overview:
      "Racing legend Sonny Hayes is coaxed out of retirement to lead a struggling Formula 1 team—and mentor a young hotshot driver—while chasing one more chance at glory.",
    poster_path: "/9PXZIUsSDh4alB80jheWX4fhZmy.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [28, 18],
    popularity: 145.9268,
    release_date: "2025-06-25",
    video: false,
    vote_average: 7.6,
    vote_count: 918,
  },
  {
    adult: false,
    backdrop_path: "/1RgPyOhN4DRs225BGTlHJqCudII.jpg",
    id: 1311031,
    title: "Demon Slayer: Kimetsu no Yaiba Infinity Castle",
    original_title: "劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来",
    overview:
      "As the Demon Slayer Corps members and Hashira engaged in a group strength training program, the Hashira Training, in preparation for the forthcoming battle against the demons, Muzan Kibutsuji appears at the Ubuyashiki Mansion. With the head of the Demon Corps in danger, Tanjiro and the Hashira rush to the headquarters but are plunged into a deep descent to a mysterious space by the hands of Muzan Kibutsuji.  The destination of where Tanjiro and Demon Slayer Corps have fallen is the demons' stronghold – the Infinity Castle. And so, the battleground is set as the final battle between the Demon Slayer Corps and the demons ignites.",
    poster_path: "/aFRDH3P7TX61FVGpaLhKr6QiOC1.jpg",
    media_type: "movie",
    original_language: "ja",
    genre_ids: [16, 28, 14, 53],
    popularity: 643.276,
    release_date: "2025-07-18",
    video: false,
    vote_average: 6.7,
    vote_count: 34,
  },
  {
    adult: false,
    backdrop_path: "/97Sl8wiR9ULc53YMfiAUf9wWbdM.jpg",
    id: 9738,
    title: "Fantastic Four",
    original_title: "Fantastic Four",
    overview:
      'During a space voyage, four scientists are altered by cosmic rays: Reed Richards gains the ability to stretch his body; Sue Storm can become invisible; Johnny Storm controls fire; and Ben Grimm is turned into a super-strong … thing. Together, these "Fantastic Four" must now thwart the evil plans of Dr. Doom and save the world from certain destruction.',
    poster_path: "/4YMcYEFS8sFuW3soP1HVmgR3cSm.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [28, 14, 878],
    popularity: 46.8947,
    release_date: "2005-06-29",
    video: false,
    vote_average: 5.793,
    vote_count: 9559,
  },
  {
    adult: false,
    backdrop_path: "/nAxGnGHOsfzufThz20zgmRwKur3.jpg",
    id: 1233413,
    title: "Sinners",
    original_title: "Sinners",
    overview:
      "Trying to leave their troubled lives behind, twin brothers return to their hometown to start again, only to discover that an even greater evil is waiting to welcome them back.",
    poster_path: "/4CkZl1LK6a5rXBqJB2ZP77h3N5i.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [27, 28, 53],
    popularity: 67.8626,
    release_date: "2025-04-16",
    video: false,
    vote_average: 7.564,
    vote_count: 2157,
  },
  {
    adult: false,
    backdrop_path: "/zNriRTr0kWwyaXPzdg1EIxf0BWk.jpg",
    id: 1234821,
    title: "Jurassic World Rebirth",
    original_title: "Jurassic World Rebirth",
    overview:
      "Five years after the events of Jurassic World Dominion, covert operations expert Zora Bennett is contracted to lead a skilled team on a top-secret mission to secure genetic material from the world's three most massive dinosaurs. When Zora's operation intersects with a civilian family whose boating expedition was capsized, they all find themselves stranded on an island where they come face-to-face with a sinister, shocking discovery that's been hidden from the world for decades.",
    poster_path: "/1RICxzeoNCAO5NpcRMIgg1XT6fm.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [878, 12, 28],
    popularity: 231.3022,
    release_date: "2025-07-01",
    video: false,
    vote_average: 6.3,
    vote_count: 817,
  },
  {
    adult: false,
    backdrop_path: "/6van4BavoNXaZhCPdzLHNQ4Uc8H.jpg",
    id: 1087891,
    title: "The Amateur",
    original_title: "The Amateur",
    overview:
      "After his life is turned upside down when his wife is killed in a London terrorist attack, a brilliant but introverted CIA decoder takes matters into his own hands when his supervisors refuse to take action.",
    poster_path: "/SNEoUInCa5fAgwuEBMIMBGvkkh.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [53, 28],
    popularity: 85.2741,
    release_date: "2025-04-09",
    video: false,
    vote_average: 6.99,
    vote_count: 947,
  },
  {
    adult: false,
    backdrop_path: "/cEQMqB3ahd4mfeUN6VGC0ouVnZZ.jpg",
    id: 1071585,
    title: "M3GAN 2.0",
    original_title: "M3GAN 2.0",
    overview:
      "After the underlying tech for M3GAN is stolen and misused by a powerful defense contractor to create a military-grade weapon known as Amelia, M3GAN's creator Gemma realizes that the only option is to resurrect M3GAN and give her a few upgrades, making her faster, stronger, and more lethal.",
    poster_path: "/oekamLQrwlJjRNmfaBE4llIvkir.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [28, 878, 53],
    popularity: 505.6093,
    release_date: "2025-06-25",
    video: false,
    vote_average: 7.63,
    vote_count: 512,
  },
  {
    adult: false,
    backdrop_path: "/oPgXVSdGR9dGwbmvIToOCMmsdc2.jpg",
    id: 541671,
    title: "Ballerina",
    original_title: "Ballerina",
    overview:
      "Taking place during the events of John Wick: Chapter 3 – Parabellum, Eve Macarro begins her training in the assassin traditions of the Ruska Roma.",
    poster_path: "/2VUmvqsHb6cEtdfscEA6fqqVzLg.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [28, 53, 80],
    popularity: 235.7576,
    release_date: "2025-06-04",
    video: false,
    vote_average: 7.496,
    vote_count: 1169,
  },
  {
    adult: false,
    backdrop_path: "/l3ycQYwWmbz7p8otwbomFDXIEhn.jpg",
    id: 803796,
    title: "KPop Demon Hunters",
    original_title: "KPop Demon Hunters",
    overview:
      "When K-pop superstars Rumi, Mira and Zoey aren't selling out stadiums, they're using their secret powers to protect their fans from supernatural threats.",
    poster_path: "/22AouvwlhlXbe3nrFcjzL24bvWH.jpg",
    media_type: "movie",
    original_language: "en",
    genre_ids: [16, 14, 35, 10402, 10751, 28],
    popularity: 214.6645,
    release_date: "2025-06-20",
    video: false,
    vote_average: 8.499,
    vote_count: 824,
  },
];
