version: '3.9'
services:
  tekmetric:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_USER=${TEKMETRIC_DEV_DB_USER}
      - POSTGRES_PASSWORD=${TEKMETRIC_DEV_DB_PASSWORD}
    volumes:
      - tekmetric:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  tekmetric:
