{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
     {{- include "backend.labels" . | nindent 4 }}
  name: {{ include "backend.fullname" . }}
spec:
  endpoints:
  - interval: 30s
    port: http
    scheme: http
    path: {{ .Values.serviceMonitor.path }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
       {{- include "backend.selectorLabels" . | nindent 6 }}
{{- end }}
