package com.interview.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;

/**
 *    Represents a customer entity within the system.
 *
 *     This class is designed to store customer information with a unique, autogenerated ID to ensure
 *     the integrity of the data and avoid the overhead of managing potential duplicate entries.
 *
 *      Indexes:
 *         - An index is created on the `birth_year` field to improve query performance, particularly when
 *           user operations involve sorting or filtering customers by their year of birth.
 */
@Entity
@Table(name = "customer", uniqueConstraints = {@UniqueConstraint(columnNames = "email")}, indexes = @Index(name = "birth_year_idx", columnList = "birth_year"))
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
public class Customer {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(nullable = false)
    private Long id;
    @Column(nullable = false)
    private String email;
    @Column(name = "first_name")
    private String firstName;
    @Column(name = "last_name")
    private String lastName;
    @Column
    private String address;
    @Column(name = "birth_year")
    private Short birthYear;
    @CreatedDate
    @Column(nullable = false, updatable = false, name = "created_at")
    private LocalDateTime createdAt;
    @LastModifiedDate
    @Column(name = "last_modified_at")
    private LocalDateTime lastModifiedAt;

}
