CREATE TABLE revinfo (
    rev INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT
);

CREATE TABLE project (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    uid VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50),

    created_by VARCHAR(255) NOT NULL,
    last_modified_by VARCHAR(255) NOT NULL,
    created_date TIMESTAMP WITH TIME ZONE NOT NULL,
    last_modified_date TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_project_status ON project(status);
CREATE INDEX idx_project_created_date ON project(created_date);

CREATE TABLE project_AUD (
    id BIGINT NOT NULL,
    rev_id INTEGER NOT NULL,
    rev_type INTEGER,

    uid VARCHAR(255),
    name VARCHAR(255),
    description TEXT,
    status VARCHAR(50),

    created_by VARCHAR(255),
    last_modified_by VARCHAR(255),
    created_date TIMESTAMP WITH TIME ZONE,
    last_modified_date TIMESTAMP WITH TIME ZONE,

    PRIMARY KEY (id, rev_id),
    CONSTRAINT fk_project_aud_rev FOREIGN KEY (rev_id) REFERENCES revinfo(rev)
);
