CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE work_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    vin VARCHAR(17) NOT NULL,
    issue_description VARCHAR(500) NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_work_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(id)
);

CREATE INDEX idx_work_orders_customer_id_id
    ON work_orders (customer_id, id);

INSERT INTO customers (name, created_at, updated_at, version)
VALUES ('Alice Johnson', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

INSERT INTO customers (name, created_at, updated_at, version)
VALUES ('Marcus Lee', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);

INSERT INTO work_orders (customer_id, vin, issue_description, status, created_at, updated_at, version)
VALUES (
    (SELECT id FROM customers WHERE name = 'Alice Johnson'),
    '1HGCM82633A004352',
    'Brake pads replacement',
    'OPEN',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
);

INSERT INTO work_orders (customer_id, vin, issue_description, status, created_at, updated_at, version)
VALUES (
    (SELECT id FROM customers WHERE name = 'Marcus Lee'),
    'JH4KA9650MC012345',
    'Check engine light diagnosis',
    'IN_PROGRESS',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP,
    0
);
