CREATE TABLE vehicle
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vin           VARCHAR(17) NOT NULL,
    make          VARCHAR(64) NOT NULL,
    make_lower    VARCHAR(64) AS (LOWER(make)),
    model         VARCHAR(64) NOT NULL,
    model_lower   VARCHAR(64) AS (LOWER(model)),
    model_year    INT         NOT NULL,
    license_plate VARCHAR(16),
    mileage       BIGINT      NOT NULL,
    created_at    TIMESTAMP   NOT NULL,
    updated_at    TIMESTAMP   NOT NULL,
    CONSTRAINT ck_vehicle_vin_uppercase CHECK (vin = UPPER(vin))
);

CREATE UNIQUE INDEX ux_vehicle_vin ON vehicle (vin);
CREATE INDEX ix_vehicle_make ON vehicle (make_lower);
CREATE INDEX ix_vehicle_model ON vehicle (model_lower);
CREATE INDEX ix_vehicle_year ON vehicle (model_year);
