CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

INSERT INTO customers (name, created_at, updated_at, version)
SELECT DISTINCT customer_name, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0
FROM work_orders;

ALTER TABLE work_orders ADD COLUMN customer_id BIGINT;

UPDATE work_orders wo
SET customer_id = (
    SELECT c.id
    FROM customers c
    WHERE c.name = wo.customer_name
);

ALTER TABLE work_orders ALTER COLUMN customer_id SET NOT NULL;

ALTER TABLE work_orders
    ADD CONSTRAINT fk_work_orders_customer FOREIGN KEY (customer_id) REFERENCES customers(id);

ALTER TABLE work_orders DROP COLUMN customer_name;
