apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "interview-app.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "interview-app.labels" . | nindent 4 }}
data:
  SPRING_APPLICATION_NAME: {{ .Values.spring.applicationName | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.spring.datasource.url | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.spring.datasource.username | quote }}
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus,metrics"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  MANAGEMENT_METRICS_TAGS_APPLICATION: {{ .Values.spring.applicationName | quote }}
  JAVA_OPTS: {{ .Values.javaOpts | quote }}
