# Generated by Django 5.1 on 2024-08-24 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_event_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="date",
            new_name="event_datetime",
        ),
    ]
