prometheus:
  prometheusSpec:
    retention: 7d
    resources:
      requests:
        memory: 400Mi
        cpu: 200m

kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false