{{- if .Values.externalSecrets.enabled -}}
# ExternalSecret is the ESO CRD that pulls from Vault (or other stores)
# and writes a native k8s Secret. The Deployment envFroms that Secret.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "tekmetric-backend.fullname" . }}-secrets
  labels:
    {{- include "tekmetric-backend.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "tekmetric-backend.fullname" . }}-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    {{- range .Values.externalSecrets.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ $.Values.externalSecrets.remoteRef.path }}
        property: {{ .remoteKey }}
    {{- end }}
{{- end }}
