### Create task
POST {{client.host.url}}/api/v1/tasks
Content-Type: application/json

{
  "jobId": 2,
  "status": "TODO",
  "title": "Oil change 2",
  "type": "Service",
  "description": "",
  "mechanicName": "John Doe"
}

### Update task
PUT {{client.host.url}}/api/v1/tasks/1
Content-Type: application/json

{
  "jobId": 1,
  "status": "COMPLETED",
  "title": "Oil change",
  "type": "Service",
  "description": "",
  "mechanicName": "John Doe"
}

### Get task by id
GET {{client.host.url}}/api/v1/tasks/2

### Delete task
DELETE {{client.host.url}}/api/v1/tasks/1
