### Create task
POST {{client.host.url}}/api/v1/tasks
Content-Type: application/json
Authorization: Bearer {{client.auth.token.admin}}

{
  "jobId": 3,
  "status": "TODO",
  "title": "Oil change 2",
  "type": "Service",
  "description": "",
  "mechanicName": "John Doe"
}

### Update task
PUT {{client.host.url}}/api/v1/tasks/1
Content-Type: application/json
Authorization: Bearer {{client.auth.token.admin}}

{
  "jobId": 1,
  "status": "COMPLETED",
  "title": "Oil change",
  "type": "Service",
  "description": "",
  "mechanicName": "John Doe"
}

### Get task by id
GET {{client.host.url}}/api/v1/tasks/2
Authorization: Bearer {{client.auth.token.admin}}

### Delete task
DELETE {{client.host.url}}/api/v1/tasks/1
Authorization: Bearer {{client.auth.token.admin}}
