// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/forecast/:locationId": {
    params: {
      "locationId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/forecast/:locationId";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/forecast.tsx": {
    id: "routes/forecast";
    page: "/forecast/:locationId";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/forecast": typeof import("./app/routes/forecast.tsx");
};