{{- if .Values.ingress.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Chart.Name }}
  namespace: hopprgg
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  hostnames:
    - {{ .Values.ingress.hostname | quote }}
  parentRefs:
    - name: cilium-gateway
      namespace: kube-system
      sectionName: https
  rules:
    - backendRefs:
        - name: {{ .Chart.Name }}
          port: {{ .Values.service.port }}
      matches:
        - path:
            type: PathPrefix
            value: /
{{- end }}
