{{- if and .Values.secrets (index .Values.secrets "kubernetes-secrets") (index .Values.secrets "kubernetes-secrets").enabled }}
{{- $kubernetesSecrets := index .Values.secrets "kubernetes-secrets" }}
{{- range $kubernetesSecrets.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  {{- if .namespace }}
  namespace: {{ .namespace }}
  {{- end }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
spec:
  type: {{ .type }}
  data:
    {{ .data }}
{{- end }}
{{- end }}
