/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as MetroStationCodesImport } from './routes/metro.$stationCodes'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MetroStationCodesRoute = MetroStationCodesImport.update({
  id: '/metro/$stationCodes',
  path: '/metro/$stationCodes',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/metro/$stationCodes': {
      id: '/metro/$stationCodes'
      path: '/metro/$stationCodes'
      fullPath: '/metro/$stationCodes'
      preLoaderRoute: typeof MetroStationCodesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/metro/$stationCodes': typeof MetroStationCodesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/metro/$stationCodes': typeof MetroStationCodesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/metro/$stationCodes': typeof MetroStationCodesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/metro/$stationCodes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/metro/$stationCodes'
  id: '__root__' | '/' | '/metro/$stationCodes'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MetroStationCodesRoute: typeof MetroStationCodesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MetroStationCodesRoute: MetroStationCodesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/metro/$stationCodes"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/metro/$stationCodes": {
      "filePath": "metro.$stationCodes.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
