spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none

# JWT Configuration
jwt.secret=05485227394f970026ba222893cefbd288468eb95751142346c1d14a7b1b2376
jwt.expiration=86400000

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when-authorized