server:
  port: 8080
  servlet:
    context-path: /tekmetric
  shutdown: graceful
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/octet-stream,application/pdf,application/javascript,text/javascript,application/vnd.ms-excel,application/zip,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/x-tar,image/png,video/mp4,image/jpeg,text/csv,text/css,*/*
    min-response-size: 1
  tomcat:
    relaxed-query-chars: "[,],|"
    threads:
      max: 512

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  sql:
    init:
      mode: always
      schema-locations: classpath:database/schema.sql
      data-locations: classpath:database/data.sql
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
  h2:
    console:
      enabled: true
  main:
    banner-mode: off

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized