insert into PRODUCT (NAME, DESCRIPTION, PRICE, VERSION, CREATED_DATE, MODIFIED_DATE)
    VALUES ( 'Chair', 'Great Chair', 5000, 0, NOW(), NOW());

insert into PRODUCT (NAME, DESCRIPTION, PRICE, VERSION, CREATED_DATE, MODIFIED_DATE, DELETED_DATE)
    VALUES ( 'Old Chair', 'Once a Great Chair', 5000, 0, TIMESTAMPADD(DAY, -2, NOW()), NOW(), NOW());