export const RecipeCardStyles = {
  card: {
    display: "flex",
    backgroundColor: "#fff",
    marginBottom: "30px",
    borderRadius: "8px",
    boxShadow: "0 4px 8px rgba(0, 0, 0, 0.1)",
    overflow: "hidden",
    textAlign: "left",
    transition: "max-height 0.3s ease",
    maxHeight: "200px",
    position: "relative",
  },
  cardExpanded: {
    maxHeight: "800px",
  },
  image: {
    width: "300px",
    height: "auto",
    objectFit: "cover",
  },
  content: {
    padding: "20px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    position: "relative",
  },
  category: {
    fontSize: "12px",
    color: "#999",
    textTransform: "uppercase",
    marginBottom: "8px",
  },
  title: {
    fontSize: "24px",
    fontWeight: "bold",
    margin: "0 0 10px 0",
  },
  truncatedDescription: {
    fontSize: "16px",
    color: "#333",
    lineHeight: "1.6",
    display: "-webkit-box",
    WebkitLineClamp: 3,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  fullDescription: {
    fontSize: "16px",
    color: "#333",
    lineHeight: "1.6",
  },
  expandedContent: {
    marginTop: "10px",
  },
  scrollableContent: {
    maxHeight: "200px",
    overflowY: "auto",
    paddingRight: "10px",
  },
  viewMoreButton: {
    backgroundColor: "transparent",
    color: "#007bff",
    border: "none",
    cursor: "pointer",
    fontSize: "14px",
    padding: "0",
    position: "absolute",
    bottom: "20px",
    right: "20px",
  },
};
