replicaCount: 2
image:
  repository: ghcr.io/hoppr-gg/interview/backend
  tag: "feature-k8s-app-mod"
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
ingress:
  enabled: true
  className: cilium
  hostname: backend.hoppr.gg
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
healthCheck:
  path: /actuator/health
  port: 8080
env: {}
nodeSelector: {}
tolerations: []
affinity: {}
