name: Backend Maven CI

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml'

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Install Maven (for act)
        if: ${{ env.ACT }}
        run: |
          MAVEN_VERSION=3.9.4
          wget https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
          sudo tar -xzf apache-maven-${MAVEN_VERSION}-bin.tar.gz -C /opt
          sudo ln -sfn /opt/apache-maven-${MAVEN_VERSION}/bin/mvn /usr/bin/mvn
          mvn --version

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Spotless Check
        working-directory: backend
        run: mvn spotless:check

      - name: Build backend with Maven
        working-directory: backend
        run: mvn clean install

      - name: Run integration tests
        working-directory: backend
        run: mvn verify -DskipUnitTests

      - name: Build Docker image
        working-directory: backend
        run: mvn docker:build

      - name: Tag Docker image
        working-directory: backend
        run: mvn docker:tag

      # Push Docker image to registry
      # Commented out, as it requires Docker Hub credentials
#      - name: Push Docker image
#        working-directory: backend
#        run: mvn docker:push