name: Backend Service Deploy

on:
  push:
    branches:
      - master
    paths:
      - backend

jobs:
  backend-ecs-deploy:
    uses: ./.github/workflows/ecs-deploy.yml
    with:
      project-directory: backend
      stack-name: backend-service
      environment: prod
    secrets: inherit
      