name: Build & Test Backend

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Maven Dependency Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          !~/.m2/repository/com/tekmetric
        key: ${{ runner.os }}-maven-${{ hashFiles('backend/**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
        
    - name: Run Spotless check
      working-directory: ./backend
      run: ./mvnw spotless:check
      
    - name: Run tests
      working-directory: ./backend
      run: ./mvnw test
      
    - name: Package application (skip tests)
      working-directory: ./backend
      run: ./mvnw package -DskipTests
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: application-jar
        path: backend/target/*.jar
