name: Migration Tests

on:
  push:
    branches: [ master ]

jobs:
  migration-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Verify migrations
      working-directory: ./backend
      run: ./mvnw test -P migration-test
    
    - name: Test application with migrations
      working-directory: ./backend
      run: ./mvnw test
